title: "Idea"
body:
  - type: textarea
    id: use_case
    attributes:
      label: Use case
      description: Describe the project situation without private content.
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Suggestion
    validations:
      required: true
